---
title: "Potsherd Photogrammetry"
author: "Karl Edwards"
date: "September 20, 2017"
output:
  github_document:
    html_preview: true
    toc: true
    toc_depth: 2
---

## Overview

- Read model data from .STL file
- Align the model with the axes and scoot it up against x = y = z = 0
- Plot the profile
- Estimate key dimensions

```{r, knitr_options, echo = FALSE, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

## Project-Specific Configuration
```{r project_specific_configuration}
filename <- 'stereolithograph.stl'

# Convenient names to improve readability
x_axis <- 1
y_axis <- 2
z_axis <- 3
axes <- 1:3
axes[ x_axis ] <- 'x'
axes[ y_axis ] <- 'y'
axes[ z_axis ] <- 'z'

# Wireframe parameters
stripe_width <- 0.0003
stripe_tol   <- 0.00003
```
## Load Libraries
```{r, libraries,echo=TRUE,include=TRUE,results='as-is'}
# General
require( rgl )
require( ggplot2 )
require( gridExtra )
require( purrr )
require( tibble )
require( lattice )
```
